[package]
name = "webp"
version = "0.2.0"
authors = ["Harrison Burt <57491488+ChillFish8@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libwebp-sys = "0.3.2"
image = "0.24"
anyhow = "1"